server:
  port: 8080

json:
  request-size-limit: 1048576 # 1m
  #request-size-limit: 1073741824 # 1g
spring:
  application:
    name: simple-demo
  profiles:
    active: dev
  servlet:
    multipart:
      enabled: true
      max-file-size: 7KB #单个文件的大小 i.e. 1MB Priority 2, This config also works for limit the upload Maximum size.
      max-request-size: 3KB #设置单次请求的文件的总大小 i.e.100KB Priority 1, Limit the multipart/form-data file upload Maximum size.

springdoc:
  pathsToMatch: /healthz, /api/**
  writer-with-default-pretty-printer: true
  api-docs.enabled: true
  api-docs.path: /springdoc/api-docs
  resolve-schema-properties: true
  swagger-ui:
    enabled: true
    path: /springdoc/docs.html
    url: /springdoc/api-docs
    displayRequestDuration: true
    showExtensions: true
    showCommonExtensions: true
    disable-swagger-default-url: true
    operationsSorter: method
swagger:
  application-name: ${spring.application.name}
  application-version: 1.0
  application-description: Springdoc Openapi Of Simple Demo
  try-host: http://localhost:8080
