server:
  ssl:
    key-store-type: PKCS12
    key-store: classpath:keys/simpledemo.p12
    key-store-password: simpledemo.sp
    key-alias: simpledemo
    enabled: true
  port: 8443
  originhttp:
    port: 8080

  max-http-header-size: 1KB #?
  tomcat:
    accept-count: 10 #no use
    max-connections: 20 #no use
    max-swallow-size: 2KB #no use
    max-http-post-size: 3KB #no use

    connection-timeout: 10s #control the SocketWrapperBase.getReadTimeout
    threads:
      max: 3

spring:
  application:
    name: simple-demo
  profiles:
    active: dev
  servlet:
    multipart:
      enabled: true
      max-file-size: 10GB #单个文件的大小 The maximum allowed size of a single uploaded file. i.e. 1MB Priority 2, This config also works for limit the upload Maximum size.
      max-request-size: 100GB #设置单次请求的文件的总大小 The maximum allowed size of a complete request. i.e. 100KB Priority 1, Limit the multipart/form-data file upload Maximum size.

#Non-dev environment should config database and set spring.profiles.active=prod
  datasource:
    url: jdbc:mysql://localhost:3306/simpledemo?useSSL=false
    username: root
    password: root

  h2:
    console:
      enabled: false

  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd'T'HH:mm:ss.SSSZ


json:
  request-size-limit: 1048576 # 1m
  #request-size-limit: 1073741824 # 1g

throttling:
  permitsPerSecond: 0.1
  timeoutMs: 1000
  message: hahaha too many