apiVersion: batch/v1
kind: CronJob
metadata:
  name: hello
  namespace: app
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: hello
              image: registry.cn-beijing.aliyuncs.com/google_registry/busybox:1.24
              args:
                - /bin/sh
                - -c
                - date; echo Hello from the Kubernetes cluster
          restartPolicy: OnFailure
