FROM grafana/grafana-oss:9.3.2
USER root
#RUN useradd -u 1234 demo && mkdir -p /custom
RUN mkdir -p /custom
COPY grafana.ini /custom
ENV GF_PATHS_CONFIG=/custom/grafana.ini
ENV GF_DASHBOARDS_JSON_ENABLED=true
ENV GF_LIVE_ALLOWED_ORIGINS='*'
#RUN chown -R demo:demo /custom
#USER demo

EXPOSE 3000
CMD ["bash"]
