apiVersion: v1
kind: Pod
metadata:
  name: test-nginx
spec:
  containers:
  - image: docker.io/nginx:latest
    imagePullPolicy: IfNotPresent
    name: test-nginx
    ports:
    - containerPort: 80
    volumeMounts:
    - mountPath: /usr/share/nginx/html # mount /d/test-data/nginx/html folder to /usr/share/nginx/html
      name: nginx-data
  volumes:
  - name: nginx-data
    hostPath:
      path: /run/desktop/mnt/host/d/tmp/nginx/html # /d means windows D disk
      type: DirectoryOrCreate
